# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username(s), e.g. [imuniqueshiv]
patreon: # Replace with a Patreon username
open_collective: # Replace with an Open Collective username
ko_fi: # Replace with a Ko-fi username
tidelift: # Replace with a Tidelift platform-name/package-name
community_bridge: # Replace with a Community Bridge project-name
liberapay: # Replace with a Liberapay username
issuehunt: # Replace with an IssueHunt username
lfx_crowdfunding: # Replace with an LFX Crowdfunding project-name
polar: # Replace with a Polar username
buy_me_a_coffee: # Replace with a Buy Me a Coffee username
thanks_dev: # Replace with a thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs, e.g. ['https://maintainerai.dev/sponsor']
