export const mockRepositories = [
  {
    id: 1,
    name: "react-components",
    owner: "vercel",
    description: "A comprehensive React component library with 100+ production-ready components",
    stars: 12500,
    forks: 1200,
    openIssues: 45,
    openPRs: 12,
    url: "https://github.com/vercel/react-components",
    language: "TypeScript",
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    healthScore: 92,
    automationEnabled: true,
    automationIssuesResolved: 234,
    automationPRsMerged: 89,
    collaborators: 34,
    topics: ["react", "components", "ui", "typescript"],
    isPrivate: false,
  },
  {
    id: 2,
    name: "next-auth",
    owner: "nextauthjs",
    description: "Authentication for Next.js applications with OAuth2 and JWT support",
    stars: 8300,
    forks: 920,
    openIssues: 28,
    openPRs: 8,
    url: "https://github.com/nextauthjs/next-auth",
    language: "TypeScript",
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    healthScore: 88,
    automationEnabled: true,
    automationIssuesResolved: 156,
    automationPRsMerged: 67,
    collaborators: 28,
    topics: ["authentication", "next.js", "oauth", "jwt"],
    isPrivate: false,
  },
  {
    id: 3,
    name: "tailwindcss",
    owner: "tailwindlabs",
    description: "A utility-first CSS framework for rapidly building custom designs",
    stars: 75000,
    forks: 4200,
    openIssues: 156,
    openPRs: 34,
    url: "https://github.com/tailwindlabs/tailwindcss",
    language: "JavaScript",
    lastUpdated: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    healthScore: 95,
    automationEnabled: true,
    automationIssuesResolved: 512,
    automationPRsMerged: 203,
    collaborators: 156,
    topics: ["css", "framework", "utility", "design"],
    isPrivate: false,
  },
  {
    id: 4,
    name: "internal-api",
    owner: "yourorg",
    description: "Internal API service for microservices communication",
    stars: 342,
    forks: 45,
    openIssues: 12,
    openPRs: 5,
    url: "https://github.com/yourorg/internal-api",
    language: "Go",
    lastUpdated: new Date(Date.now() - 6 * 60 * 60 * 1000),
    healthScore: 76,
    automationEnabled: false,
    automationIssuesResolved: 0,
    automationPRsMerged: 0,
    collaborators: 8,
    topics: ["api", "microservices", "go"],
    isPrivate: true,
  },
];

export const mockIssues = [
  {
    id: 1,
    number: 2534,
    title: "Performance improvement for large lists",
    repository: "react-components",
    status: "open",
    priority: "high",
    labels: ["performance", "optimization", "bug"],
    author: "john-dev",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    description:
      "The component renders slowly when handling 1000+ items. Need to implement virtualization.",
    comments: 24,
    aiGenerated: true,
  },
  {
    id: 2,
    number: 2535,
    title: "Add dark mode support",
    repository: "react-components",
    status: "open",
    priority: "medium",
    labels: ["feature", "ui", "enhancement"],
    author: "sarah-ui",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    description: "Implement CSS variables for theme switching across all components.",
    comments: 8,
    aiGenerated: false,
  },
  {
    id: 3,
    number: 1203,
    title: "Type definitions missing for utils",
    repository: "next-auth",
    status: "open",
    priority: "low",
    labels: ["types", "documentation"],
    author: "mike-types",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    description: "Several utility functions lack proper TypeScript type definitions.",
    comments: 3,
    aiGenerated: true,
  },
  {
    id: 4,
    number: 156,
    title: "Handle edge case in string validation",
    repository: "internal-api",
    status: "open",
    priority: "medium",
    labels: ["bug", "validation"],
    author: "dev-team",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    description: "Empty strings are not being properly validated in the request handler.",
    comments: 5,
    aiGenerated: true,
  },
];

export const mockPullRequests = [
  {
    id: 1,
    number: 5123,
    title: "Refactor authentication flow",
    repository: "react-components",
    status: "review",
    author: "alex-dev",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    additions: 234,
    deletions: 89,
    comments: 12,
    description: "Streamlined authentication to reduce bundle size by 15%.",
    reviewRequests: 3,
    aiReviewCompleted: true,
  },
  {
    id: 2,
    number: 1204,
    title: "Add new API endpoints",
    repository: "next-auth",
    status: "approved",
    author: "emma-api",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    additions: 567,
    deletions: 123,
    comments: 8,
    description: "Introduce new OAuth2 endpoints for better provider support.",
    reviewRequests: 0,
    aiReviewCompleted: true,
  },
  {
    id: 3,
    number: 892,
    title: "Update dependencies and fix security issues",
    repository: "tailwindcss",
    status: "merged",
    author: "dependabot",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    additions: 45,
    deletions: 32,
    comments: 2,
    description: "Automated dependency updates for security patches.",
    reviewRequests: 0,
    aiReviewCompleted: false,
  },
];

export const mockDashboardStats = {
  totalRepositories: 24,
  totalIssues: 342,
  openIssues: 156,
  closedIssues: 186,
  totalPRs: 89,
  openPRs: 23,
  mergedPRs: 66,
  averageIssueResolutionTime: "4.2 days",
  averagePRReviewTime: "1.8 days",
};

export const mockActivityTimeline: Array<{
  id: number
  type: 'issue' | 'pr'
  title: string
  action: string
  timestamp: Date
  repository: string
  author: string
}> = [
  {
    id: 1,
    type: "issue",
    title: "Performance improvement for large lists",
    action: "created",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    repository: "react-components",
    author: "john-dev",
  },
  {
    id: 2,
    type: "pr",
    title: "Refactor authentication flow",
    action: "merged",
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    repository: "react-components",
    author: "alex-dev",
  },
  {
    id: 3,
    type: "issue",
    title: "Add dark mode support",
    action: "closed",
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    repository: "react-components",
    author: "sarah-ui",
  },
  {
    id: 4,
    type: "pr",
    title: "Update dependencies and fix security issues",
    action: "merged",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    repository: "tailwindcss",
    author: "dependabot",
  },
  {
    id: 5,
    type: "issue",
    title: "Type definitions missing for utils",
    action: "commented",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    repository: "next-auth",
    author: "dev-team",
  },
];

export const mockTeamMembers = [
  {
    id: 1,
    name: "Alex Johnson",
    email: "alex@example.com",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    joinedAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    name: "Sarah Chen",
    email: "sarah@example.com",
    role: "developer",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    joinedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
  },
  {
    id: 3,
    name: "Mike Rodriguez",
    email: "mike@example.com",
    role: "developer",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    joinedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
  },
];

export const mockNotifications = [
  {
    id: 1,
    type: "pr_merged",
    title: "PR #5123 merged successfully",
    description: "Refactor authentication flow has been merged into main",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
  },
  {
    id: 2,
    type: "issue_assigned",
    title: "Issue #2534 assigned to you",
    description: "Performance improvement for large lists",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    read: false,
  },
  {
    id: 3,
    type: "review_requested",
    title: "Review requested on PR #1204",
    description: "Add new API endpoints",
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    read: true,
  },
];

// Health Center Data
export const mockRepositoryHealth = {
  1: {
    repositoryId: 1,
    codeQuality: 88,
    documentation: 92,
    issueBacklog: 45,
    prBacklog: 12,
    contributorActivity: 87,
    ciStatus: "passing",
    releaseFrequency: "2 weeks",
    automationCoverage: 94,
    securityAlerts: 0,
    dependencyHealth: 91,
    lastHealthCheck: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  2: {
    repositoryId: 2,
    codeQuality: 85,
    documentation: 78,
    issueBacklog: 28,
    prBacklog: 8,
    contributorActivity: 82,
    ciStatus: "passing",
    releaseFrequency: "3 weeks",
    automationCoverage: 88,
    securityAlerts: 2,
    dependencyHealth: 84,
    lastHealthCheck: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  3: {
    repositoryId: 3,
    codeQuality: 96,
    documentation: 95,
    issueBacklog: 156,
    prBacklog: 34,
    contributorActivity: 95,
    ciStatus: "passing",
    releaseFrequency: "1 month",
    automationCoverage: 97,
    securityAlerts: 0,
    dependencyHealth: 96,
    lastHealthCheck: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
};

// AI Insights Data
export const mockAIInsights: Array<{
  id: number
  repositoryId: number
  title: string
  description: string
  severity: 'low' | 'medium' | 'high'
  confidence: number
  suggestedAction: string
  quickFixAvailable: boolean
  category: string
}> = [
  {
    id: 1,
    repositoryId: 1,
    title: "Documentation is outdated",
    description: "The README.md hasn't been updated in 60 days",
    severity: "medium",
    confidence: 92,
    suggestedAction: "Review and update the documentation",
    quickFixAvailable: true,
    category: "documentation",
  },
  {
    id: 2,
    repositoryId: 1,
    title: "27 stale issues detected",
    description: "Issues without activity for 90+ days",
    severity: "high",
    confidence: 98,
    suggestedAction: "Close or update stale issues",
    quickFixAvailable: true,
    category: "issues",
  },
  {
    id: 3,
    repositoryId: 2,
    title: "No release in 90 days",
    description: "Last release was 93 days ago",
    severity: "high",
    confidence: 100,
    suggestedAction: "Plan and publish a new release",
    quickFixAvailable: false,
    category: "releases",
  },
  {
    id: 4,
    repositoryId: 1,
    title: "Large PR waiting review",
    description: "PR #5123 has 450+ lines and is waiting 5 days for review",
    severity: "medium",
    confidence: 85,
    suggestedAction: "Prioritize review or split into smaller PRs",
    quickFixAvailable: false,
    category: "prs",
  },
];

// Contributor Analytics Data
export const mockContributors = [
  {
    id: 1,
    login: "alex-dev",
    name: "Alex Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex-dev",
    contributions: 234,
    isMainMaintainer: true,
    averageReviewTime: "2.1 hours",
    averageMergeTime: "1.5 days",
    openPRCount: 3,
    issuesSolved: 45,
    joinedAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000),
    lastActive: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 2,
    login: "sarah-ui",
    name: "Sarah Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah-ui",
    contributions: 156,
    isMainMaintainer: false,
    averageReviewTime: "4.5 hours",
    averageMergeTime: "2.1 days",
    openPRCount: 2,
    issuesSolved: 28,
    joinedAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000),
    lastActive: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: 3,
    login: "mike-types",
    name: "Mike Rodriguez",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=mike-types",
    contributions: 89,
    isMainMaintainer: false,
    averageReviewTime: "6.2 hours",
    averageMergeTime: "3.1 days",
    openPRCount: 1,
    issuesSolved: 12,
    joinedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    lastActive: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
];

// Automation Center Data
export const mockAutomations = [
  {
    id: 1,
    name: "Issue Claim System",
    enabled: true,
    status: "active",
    runs: 342,
    successRate: 98,
    lastExecution: new Date(Date.now() - 4 * 60 * 60 * 1000),
    description: "Automatically assign issues to users who comment 'I want to take this'",
  },
  {
    id: 2,
    name: "Auto Labels",
    enabled: true,
    status: "active",
    runs: 892,
    successRate: 94,
    lastExecution: new Date(Date.now() - 2 * 60 * 60 * 1000),
    description: "Automatically label issues and PRs based on content",
  },
  {
    id: 3,
    name: "Stale Issues",
    enabled: true,
    status: "active",
    runs: 156,
    successRate: 100,
    lastExecution: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    description: "Mark and close issues with no activity for 90 days",
  },
  {
    id: 4,
    name: "Welcome Messages",
    enabled: true,
    status: "active",
    runs: 234,
    successRate: 97,
    lastExecution: new Date(Date.now() - 6 * 60 * 60 * 1000),
    description: "Post welcome message on first-time contributor PRs",
  },
  {
    id: 5,
    name: "PR Checks",
    enabled: true,
    status: "active",
    runs: 1203,
    successRate: 96,
    lastExecution: new Date(Date.now() - 1 * 60 * 60 * 1000),
    description: "Run automated checks on pull requests",
  },
  {
    id: 6,
    name: "Auto Assignment",
    enabled: false,
    status: "inactive",
    runs: 0,
    successRate: 0,
    lastExecution: null,
    description: "Automatically assign PRs to team members",
  },
];

// GitHub App Management Data
export const mockGitHubApp = {
  name: "MaintainerAI Bot",
  installationId: "app_12345",
  status: "active",
  installedRepositories: 4,
  permissions: [
    { name: "contents", access: "read-write" },
    { name: "issues", access: "read-write" },
    { name: "pull_requests", access: "read-write" },
    { name: "workflows", access: "read" },
  ],
  webhookStatus: "active",
  webhookEvents: [
    "issues",
    "pull_request",
    "pull_request_review",
    "issue_comment",
  ],
  rateLimit: { remaining: 4950, limit: 5000 },
  lastSync: new Date(Date.now() - 2 * 60 * 60 * 1000),
  syncStatus: "completed",
};
